### ISSUE TITLE
Problem with C++ compiler during installation under R 3.6

### ISSUE THREAD

**Issue by DavidBreuer** [RInstitute/dqmagic#7]
After upgrading to R 3.6, I get a C++ compiler error when installing dqmagic:

``` 
> install.packages("dqmagic_0.0.3.tar.gz", repos = NULL, type="source")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘dqmagic’ ...
** using staged installation
checking whether the C++ compiler works... no
configure: error: in `/tmp/RtmphLPkAd/R.INSTALL205f685bc685/dqmagic':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
```

Since the config.log mentions problems with CXX1 and similar, I commented out some lines in the package configure file below the following line:

```
# use deprecated CXX1X* to support R versions 3.1.0 to 3.3.3
```

This is a workaround that worked for me. But perhaps, according to the comment above, it may cause problems with other R versions?

Thanks and best!

**Comment by rstub** [comment]
Proper solution would be to use `CXX1X` for R version < 3.4.0 and `CXX11` otherwise. Will fix this in a minute.
